[irc.myirc]
Server="irc.fi.ircnet.net:6667"
Nick="yourbotname"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[telegram.mytelegram]
#See https://core.telegram.org/bots#6-botfather 
#and https://www.linkedin.com/pulse/telegram-bots-beginners-marco-frau
Token=""
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[discord.mydiscord]
# You can get your token by following the instructions on
# https://github.com/42wim/matterbridge/wiki/Discord-bot-setup
# If you want roles/groups mentions to be shown with names instead of ID, 
# you'll need to give your bot the "Manage Roles" permission.
Token=""
Server="testi12345" # picked from guilds the bot is connected to
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="gateway1"
enable=true


[[gateway.inout]]
account="discord.mydiscord"
channel="general"

[[gateway.inout]]
account="irc.myirc"
channel=""

[[gateway.inout]]
account="telegram.mytelegram"
channel=""